DATASET:
  TYPE: VLNR2R-v1
  SPLIT: train
  DATA_PATH: "data/datasets/vln/r2r/v1/{split}/R2R_{split}.json.gz"
  CONNECTIVITY_PATH: "data/datasets/vln/r2r/v1/connectivity/connectivity.json"
  SCENES_DIR: "data/scene_datasets/"
