ENVIRONMENT:
  MAX_EPISODE_STEPS: 30
SIMULATOR:
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR']
  FORWARD_STEP_SIZE: 1.20
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    GPU_GPU: False
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 80
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 80
TASK:
  DISCRETE: True
  TYPE: VLN-v1
  SUCCESS_DISTANCE: 3.0
  SENSORS: ['HEADING_SENSOR', "ADJACENT_VIEWPOINTS_SENSOR", "ELEVATION_SENSOR"]
  ADJACENT_VIEWPOINTS_SENSOR:
    CONNECTIVITY_PATH: "data/datasets/vln/r2r/v1/connectivity/"
  POSSIBLE_ACTIONS: ["STOP", 'MOVE_FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'LOOK_UP', "LOOK_DOWN", "TELEPORT"]
  MEASUREMENTS: ['SPL', 'NAVIGATION_ERROR', 'TRAJECTORY_LENGTH', 'ORACLE_SUCCESS', 'SUCCESS', 'DISTANCE_TO_GOAL']
  SPL:
    TYPE: SPL
    SUCCESS_DISTANCE: 3.0
DATASET:
  TYPE: VLNR2R-v1
  SPLIT: train
  DATA_PATH: "data/datasets/vln/r2r/v1/{split}/R2R_{split}.json.gz"
  SCENES_DIR: "data/scene_datasets/"
